---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasp
  labels:
    app: rasp
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rasp
    spec:
      # hostNetwork: true
      securityContext:
        fsGroup: 999
      enableServiceLinks: false
      initContainers:
        - name: rasp-init
          image: ghcr.io/bschapendonk/rasp:main
          imagePullPolicy: Always
          resources: {}
          command:
            - sh
            - -c
            - set -eux && cp -vL /tmp/key/* /tmp/etc && cp -vL /etc/ripe-atlas/* /tmp/etc && chmod 600 /tmp/etc/*
          volumeMounts:
            - name: data
              mountPath: /tmp/etc
            - name: key
              mountPath: /tmp/key
      containers:
        - name: rasp-probe
          image: ghcr.io/bschapendonk/rasp:main
          imagePullPolicy: Always
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /etc/ripe-atlas
      volumes:
        - name: key
          secret:
            secretName: rasp
        - name: data
          emptyDir: {}
